services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - redis

  client:
    build:
      context: ./client
    ports:
      - "8080:80"
    env_file:
      - ./client/.env
    depends_on:
      - server

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/src/config/db-init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  redis-data:
  postgres-data:
